export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'


export const PRODUCT_LIST_REQUEST2 = 'PRODUCT_LIST_REQUEST2'
export const PRODUCT_LIST_SUCCESS2 = 'PRODUCT_LIST_SUCCESS2'
export const PRODUCT_LIST_FAIL2 = 'PRODUCT_LIST_FAIL2'


export const PRODUCT_LIST_REQUEST3 = 'PRODUCT_LIST_REQUEST3'
export const PRODUCT_LIST_SUCCESS3 = 'PRODUCT_LIST_SUCCESS3'
export const PRODUCT_LIST_FAIL3 = 'PRODUCT_LIST_FAIL3'


export const PRODUCT_LIST_REQUEST4 = 'PRODUCT_LIST_REQUEST4'
export const PRODUCT_LIST_SUCCESS4 = 'PRODUCT_LIST_SUCCESS4'
export const PRODUCT_LIST_FAIL4 = 'PRODUCT_LIST_FAIL4'


export const BRAND_LIST_REQUEST = 'BRAND_LIST_REQUEST'
export const BRAND_LIST_SUCCESS = 'BRAND_LIST_SUCCESS'
export const BRAND_LIST_FAIL = 'BRAND_LIST_FAIL'


export const PRODUCT_LIST_DISCOUNT_REQUEST = 'PRODUCT_LIST_DISCOUNT_REQUEST'
export const PRODUCT_LIST_DISCOUNT_SUCCESS = 'PRODUCT_LIST_DISCOUNT_SUCCESS'
export const PRODUCT_LIST_DISCOUNT_FAIL = 'PRODUCT_LIST_DISCOUNT_FAIL'

export const PRODUCT_LIST_ARRAVEL_REQUEST = 'PRODUCT_LIST_ARRAVEL_REQUEST'
export const PRODUCT_LIST_ARRAVEL_SUCCESS = 'PRODUCT_LIST_ARRAVEL_SUCCESS'
export const PRODUCT_LIST_ARRAVEL_FAIL = 'PRODUCT_LIST_ARRAVEL_FAIL'



export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'


export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'


export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'


export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'


export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'


